# -*- coding: utf-8 -*-
"""
/***************************************************************************
 3DGeoModeler
                                 A QGIS plugin
 A suite of tools and guides for generating surfaces and 3D models.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-12
        copyright            : (C) 2024 by Esbern Holmes /Roskilde University
        email                : holmes@ruc.dk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load 3DGeoModeler class from file 3DGeoModeler.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .3D_geo_modeler import 3DGeoModeler
    return 3DGeoModeler(iface)
