# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geo_modeler_3D_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeoModeler3DDialogBase(object):
    def setupUi(self, GeoModeler3DDialogBase):
        GeoModeler3DDialogBase.setObjectName("GeoModeler3DDialogBase")
        GeoModeler3DDialogBase.resize(400, 300)

        self.retranslateUi(GeoModeler3DDialogBase)
        QtCore.QMetaObject.connectSlotsByName(GeoModeler3DDialogBase)

    def retranslateUi(self, GeoModeler3DDialogBase):
        _translate = QtCore.QCoreApplication.translate
        GeoModeler3DDialogBase.setWindowTitle(_translate("GeoModeler3DDialogBase", "3D GeoModeler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GeoModeler3DDialogBase = QtWidgets.QDialog()
    ui = Ui_GeoModeler3DDialogBase()
    ui.setupUi(GeoModeler3DDialogBase)
    GeoModeler3DDialogBase.show()
    sys.exit(app.exec_())
